services:
  backend:
    build: .
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./FE
      dockerfile: DockerfileFE
    ports:
      - "8081:80"
    depends_on:
      - backend